dist: focal
os: linux
language: c
services:
  - docker
script:
  - env
  - pwd
  - ls -al
  - uname -a
  - whoami
  - df
  - apt-cache search linux-modules
  - ls -al /lib/modules
  - ls -al /usr/src
