dist: focal
os: linux
language: c
services:
  - docker
script:
  - env
  - pwd
  - ls -al
  - uname -a
  - whoami
  - df
  - sudo apt install -y linux-modules-extra-5.4.0-1038-gcp
  - sudo modprobe mpls-router mpls-iptunnel
  - apt-cache search linux-modules
  - ls -al /lib/modules
  - ls -al /usr/src
